### ISSUE TITLE
怎么用这个项目在linux服务器中控制米家设备中的灯的开关

### ISSUE THREAD

**Issue by yyzhou0811** [zzyss86/mi-aqara-sdk#2]
我新建了一个js文件test.js,代码如下:
const MiAqara = require('mi-aqara-sdk');

MiAqara.create([{
   sid: '7811dcb90fb3',
   password: '9432979075174A29'
}], {
   onReady () { // Íø¹Ø¼°×ÓÉè±¸ÒÑÕÒµ½, ¶à¸öÍø¹Ø¿ÉÄÜ»áµ÷ÓÃ¶à´Î
     //console.log('onReady', msg);
    },
   onMessage () { // ËùÓÐÏûÏ¢ÀàÐÍ
     //console.log('onMessage', msg);
    }
});
MiAqara.start();

console.log(MiAqara.getGatewayBySid('7811dcb90fb3'));
console.log(MiAqara.getDevicesByGatewaySid('7811dcb90fb3'));
//console.log(MiAqara.getDevicesByModel('switch'));
//MiAqara.controlLight({sid:'7811dcb90fb3',power:true});
MiAqara.controlLight({sid:'7811dcb90fb3',power:false});
//console.log(MiAqara.getDevicesByGatewaySid('7811dcb90fb3'));
//console.log(MiAqara.getDeviceBySid('158d00021177c0'));
//console.log(MiAqara.getDeviceList())
//console.log(MiAqara.getDevicesByGatewaySidAndModel('7811dcb90fb3', 'switch'));
//console.log(MiAqara.getGatewayList());

然后使用node test.js执行命令会报错，
crypto.js:146
  var ret = this._handle.update(data, inputEncoding);
                         ^

TypeError: Cipher data must be a string or a buffer
    at TypeError (native)
    at Cipheriv.update (crypto.js:146:26)
    at Object.cipher (/root/node_modules/mi-aqara-sdk/libs/utils.js:40:26)
    at GatewayHelper.write (/root/node_modules/mi-aqara-sdk/libs/GatewayHelper.js:127:34)
    at GatewayHelper.controlLight (/root/node_modules/mi-aqara-sdk/libs/GatewayHelper.js:158:14)
    at Object.<anonymous> (/root/node_modules/test.js:20:9)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)

不能控制灯的开关，用米家可以控制灯的开关，跪求，麻烦帮忙看看,而且也获取不到子设备列表

**Comment by GitCHQL** [comment]
你的网关是啥 如果是空调伴侣是不支持这个版本的协议
，需要改写

**Comment by yyzhou0811** [comment]
我的网关sid就是7811dcb90fb3这个，按照这个文档在米家里面找的，不是空调伴侣，是米家多功能网关

**Comment by GitCHQL** [comment]
你的亮灯
操作代码要写到onready里，才不会报错，子设备也是

**Comment by yyzhou0811** [comment]
这个应该怎么写到onready里面啊，比如说我的子设备信息如下：子设备信息: 
{ Model: lumi.ctrl_neutral2.v1,did: lumi.158d00021177c0,name: 1303过道灯/8591产品灯 }{ Model: lumi.ctrl_neutral2.v1,did: lumi.158d00021177c6,name: 13F机房过道/13F技术团队 }{ Model: lumi.ctrl_neutral2.v1,did: lumi.158d0002233967,name: 13休闲区/楼道 }{ Model: lumi.ctrl_neutral2.v1,did: lumi.158d0002233994,name: 技术团队过道灯/13走廊桶灯 }{ Model: lumi.ctrl_neutral2.v1,did: lumi.158d000223399f,name: 13楼茶水间灯/1303过道桶灯 }{ Model: lumi.ctrl_neutral2.v1,did: lumi.158d00022339a9,name: 8591客服/8591产品 }

现在我想要13休闲区/楼道的灯打开和关闭，我应该怎么写呢

**Comment by yyzhou0811** [comment]
const MiAqara = require('mi-aqara-sdk');

MiAqara.create([{
   sid: '7811dcb90fb3',
   password: '9432979075174A29'
}], {
   onReady (msg) { // 网关及子设备已找到, 多个网关可能会调用多次
     //console.log('onReady', msg);
     MiAqara.controlLight({sid:'7811dcb90fb3',power:false});
    },
   onMessage (msg) { // 所有消息类型
     //console.log('onMessage', msg);
    }
});
MiAqara.start();

我现在这样写已经能获取到子设备信息了，但是不能开关灯，这个开关灯应该怎么实现啊，麻烦告知下

**Comment by yyzhou0811** [comment]
const MiAqara = require('mi-aqara-sdk');

MiAqara.create([{
   sid: '7811dcb90fb3',
   password: '9432979075174A29'
}], {
   onReady (msg) { // 网关及子设备已找到, 多个网关可能会调用多次
     //console.log('onReady', msg);
     //MiAqara.controlLight({sid:'7811dcb90fb3',power:false});
     MiAqara.change({"sid":"158d0002233967","data":"{\"voltage\":3300,\"channel_0\":\"off\",\"channel_1\":\"off\"}"});
     //console.log(MiAqara.getDeviceBySid('158d0002233994'));
    },
   onMessage (msg) { // 所有消息类型
     //console.log('onMessage', msg);
    Aqara.}
});
MiAqara.start();

我用MiAqara.change({"sid":"158d0002233967","data":"{\"voltage\":3300,\"channel_0\":\"off\",\"channel_1\":\"off\"}"}); 这个命令提示我 Param error 参数错误，这样写应该没有问题吧，不知道这里参数哪里有问题

**Comment by GitCHQL** [comment]
你试试sid和data不加双引号

**Comment by yyzhou0811** [comment]
不加引号也不行，也会报参数错误

**Comment by GitCHQL** [comment]
你发出来看看，而且电压不应该写在参数里吧。。。我这里暂时没有发现程序的bug。你可以多查查文档。

**Comment by yyzhou0811** [comment]
const MiAqara = require('mi-aqara-sdk');

MiAqara.create([{
   sid: '7811dcb90fb3',
   password: '9432979075174A29'
}], {
   onReady (msg) { // 网关及子设备已找到, 多个网关可能会调用多次
     //console.log('onReady', msg);
     //MiAqara.controlLight({sid:'7811dcb90fb3',power:false});
     //console.log(MiAqara.getDeviceBySid('158d0002233967'));
     MiAqara.change({sid:"158d0002233967",data:"{\"voltage\":3300,\"channel_0\":\"off\",\"channel_1\":\"off\"}"});

    },
   onMessage (msg) { // 所有消息类型
     //console.log('onMessage', msg);
    }
});
MiAqara.start();

这个是我写的test.js文件，然后运行命令为node test,js，然后报下面错误:
[root@localhost node_modules]# node test.js
[Send] msg: {"cmd":"whois"}
server is listening on port 9898.
[Message] cmd: iam, msg:  {"cmd":"iam","port":"9898","sid":"7811dcb90fb3","model":"gateway","proto_version":"1.0.9","ip":"192.168.3.111"}
[GatewayHelper:getIdList] sid:7811dcb90fb3
[Send] msg: {"cmd":"get_id_list"}
[Message] cmd: get_id_list_ack, msg:  {"cmd":"get_id_list_ack","sid":"7811dcb90fb3","token":"Aklw913GhtOv72fx","data":"[\"158d0002233967\",\"158d0002233994\",\"158d000223399f\",\"158d00021177c0\",\"158d00021177c6\",\"158d00022339a9\"]"}
[DeviceHelper:readAll] sidList=158d0002233967,158d0002233994,158d000223399f,158d00021177c0,158d00021177c6,158d00022339a9
[DeviceHelper:read] sid=158d0002233967
[Send] msg: {"cmd":"read","sid":"158d0002233967"}
[DeviceHelper:read] sid=158d0002233994
[Send] msg: {"cmd":"read","sid":"158d0002233994"}
[DeviceHelper:read] sid=158d000223399f
[Send] msg: {"cmd":"read","sid":"158d000223399f"}
[DeviceHelper:read] sid=158d00021177c0
[Send] msg: {"cmd":"read","sid":"158d00021177c0"}
[DeviceHelper:read] sid=158d00021177c6
[Send] msg: {"cmd":"read","sid":"158d00021177c6"}
[DeviceHelper:read] sid=158d00022339a9
[Send] msg: {"cmd":"read","sid":"158d00022339a9"}
[Message] cmd: read_ack, msg:  {"cmd":"read_ack","model":"ctrl_neutral2","sid":"158d0002233967","short_id":59282,"data":"{\"voltage\":3300,\"channel_0\":\"on\",\"channel_1\":\"on\"}"}
[Message] cmd: read_ack, msg:  {"cmd":"read_ack","model":"ctrl_neutral2","sid":"158d0002233994","short_id":1565,"data":"{\"voltage\":3300,\"channel_0\":\"on\",\"channel_1\":\"on\"}"}
[Message] cmd: read_ack, msg:  {"cmd":"read_ack","model":"ctrl_neutral2","sid":"158d000223399f","short_id":33388,"data":"{\"voltage\":3300,\"channel_0\":\"on\",\"channel_1\":\"on\"}"}
[Message] cmd: read_ack, msg:  {"cmd":"read_ack","model":"ctrl_neutral2","sid":"158d00021177c0","short_id":6606,"data":"{\"voltage\":3300,\"channel_0\":\"on\",\"channel_1\":\"on\"}"}
[Message] cmd: read_ack, msg:  {"cmd":"read_ack","model":"ctrl_neutral2","sid":"158d00021177c6","short_id":32711,"data":"{\"voltage\":3300,\"channel_0\":\"on\",\"channel_1\":\"on\"}"}
[Message] cmd: read_ack, msg:  {"cmd":"read_ack","model":"ctrl_neutral2","sid":"158d00022339a9","short_id":59523,"data":"{\"voltage\":3300,\"channel_0\":\"on\",\"channel_1\":\"on\"}"}
[DeviceHelper:change] sid=158d0002233967
[DeviceHelper:change] Param error

**Comment by yyzhou0811** [comment]
您能发送一份你写好的控制灯开关的js代码给我参考下吗，因为本人对js语法不是很懂，所以排查问题有点困难，麻烦你了，万分感谢

**Comment by yyzhou0811** [comment]
非常感谢这几天的沟通，我这边问题解决了，非常感谢你

**Comment by GitCHQL** [comment]
嗯 ，是不是双引号有错误.

**Comment by yyzhou0811** [comment]
不是，电压写进参数里面了，就是你说的那个问题，而且语法格式有点问题

**Comment by yyzhou0811** [comment]
还有个问题我想请教下，这个我可以使用url控制灯的开关吗？这个应该怎么做啊

**Comment by yyzhou0811** [comment]
我现在把我写的这个js文件写到定时任务计划了，周一到周五执行这个js文件开关灯，但是现在有个问题，用node执行这个js文件是在前台运行的，不会终止，定时任务计划执行完这个js文件后会在后台一直运行，多出一个进程，那这个定时任务计划执行一次多一个进程，执行一次多一个进程，有没有什么办法让这个js文件开灯后和关灯后退出程序，我的定时任务如下:
#关灯
40 12 * * 1-5 /usr/local/bin/node /root/node_modules/down.js >/dev/null 2>&1 
#开灯
30 13 * * 1-5 /usr/local/bin/node /root/node_modules/open.js >/dev/null 2>&1

**Comment by GitCHQL** [comment]
开关灯是做啥的，你要一直运行的话日期信息可以再js判断啊

**Comment by yyzhou0811** [comment]
这个就是开灯的代码:
const MiAqara = require('mi-aqara-sdk');

MiAqara.create([{
   sid: '7811dcb90fb3',
   password: '9432979075174A29'
}], {
   onReady (msg) { // 网关及子设备已找到, 多个网关可能会调用多次
     //console.log('onReady', msg);
     //MiAqara.controlLight({sid:'7811dcb90fb3',power:false});
     //console.log(MiAqara.getDeviceBySid('158d0002233967'));
       MiAqara.change({
              sid: '158d0002233967',  //13休闲区/楼道
              data: {
                    "channel_0": "on" 
                    //"channel_1": "on"
                     }        })
       MiAqara.change({
              sid: '158d0002233994',  //技术团队过道灯/13走廊桶灯
              data: {
                    "channel_0": "on",
                    "channel_1": "on"
                     }        })
       MiAqara.change({
              sid: '158d000223399f',  //13楼茶水间灯/1303过道桶灯
              data: {
                    "channel_0": "on",
                    "channel_1": "on"
                     }        })
       MiAqara.change({
              sid: '158d00021177c0',  //1303过道灯/8591产品灯
              data: {
                    "channel_0": "on",
                    "channel_1": "on"
                     }        })
        MiAqara.change({
              sid: '158d00021177c6',  //13F机房过道/13F技术团队
              data: {
                    "channel_0": "on",
                    "channel_1": "on"
                     }        })
        MiAqara.change({
              sid: '158d00022339a9',  //8591客服/8591产品
              data: {
                    //"channel_0": "on",
                    "channel_1": "on"
                     }        })
    },
   onMessage (msg) { // 所有消息类型
     //console.log('onMessage', msg);
   }
});
MiAqara.start();

**Comment by GitCHQL** [comment]
不太清楚你的需求，只是要执行完退出么？

**Comment by GitCHQL** [comment]
process.exit() 一般可以用这个

**Comment by yyzhou0811** [comment]
是的，我用node open.js 这条命令执行这个js脚本，这个灯亮了，但是会一直在前台运行啊，没有退出，我现在就是想用node open.js执行这天命令后，灯开了，这个进程也退出了，不再在前台运行

**Comment by GitCHQL** [comment]
setTimeout(function () {
        process.exit(1)
    },5000)
写在最底下

**Comment by yyzhou0811** [comment]
可以啦，哈哈，开心，原谅我这个菜鸟总是麻烦你哈

**Comment by GitCHQL** [comment]
客气，主要还是SDK写得好。我也用的他的

**Comment by yyzhou0811** [comment]
嗯，赞赞赞，开源精神

**Comment by rongyan6** [comment]
赞两位！
